apiVersion: v2
name: dploy
description: A Helm chart for Dploy - on-demand Kubernetes environments via an operator + API
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - dploy
  - operator
  - flux
  - kubernetes
  - environments
home: https://github.com/AYDEV-FR/dploy
sources:
  - https://github.com/AYDEV-FR/dploy
maintainers:
  - name: AYDEV-FR
