apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dploy.fullname" . }}-environments
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dploy.labels" . | nindent 4 }}
data:
  environments.yaml: |
    environments:
    {{- range .Values.environments }}
      - name: {{ .name | quote }}
        description: {{ .description | quote }}
        chart: {{ .chart | quote }}
        enabled: {{ .enabled }}
        visible: {{ .visible | quote }}
        icon: {{ .icon | quote }}
        {{- if .ttl }}
        ttl: {{ .ttl }}
        {{- end }}
        {{- if .extraValues }}
        extraValues: |
{{ .extraValues | indent 10 }}
        {{- end }}
    {{- end }}
