apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dploy.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dploy.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWKS_URL: {{ .Values.auth.jwksURL | quote }}
  JWT_ISSUER: {{ .Values.auth.jwtIssuer | quote }}
  {{- if .Values.auth.oidcIssuer }}
  OIDC_ISSUER: {{ .Values.auth.oidcIssuer | quote }}
  {{- end }}
  {{- if .Values.auth.oidcPublicIssuer }}
  OIDC_PUBLIC_ISSUER: {{ .Values.auth.oidcPublicIssuer | quote }}
  {{- end }}
  {{- if .Values.auth.oidcClientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.auth.oidcClientSecret | quote }}
  {{- end }}
